### PR TITLE
Fix for grid row names.

### PR DESCRIPTION
**Pull request by karthiknadig**
#3773

### CODE REVIEW

**Comment by AlexanderSher** [comment]
@int19h , can you please take a look?

**Comment by int19h** [comment]
This is not sufficient, because it will still mangle NA row names when they're numeric. 

To fix that, after checking for `is.numeric` and doing `format`, it should look for string `"NA"` in the resulting vector, and replace all instances of that with `NULL`. 

Note that regular vectors and lists can't have numeric rownames, which is why it's a bit tricky to test. If I remember correctly, the case where this happens is when you work with time series, or `quantmod` objects.

**Comment by karthiknadig** [comment]
@int19h NULL cannot be assigned to a vector.
```
> x <- c(1,2,3,4,NA,6, NA, NaN, 9)
> length(x)
[1] 9
> y<-format(x, trim = TRUE, justify = "none")
> y[y=="NA"] <- NULL
Error in y[y == "NA"] <- NULL : replacement has length zero
```
Attempting to convert to list, then assigning NULL removes it 
```
> z <- as.list(y)
> z[z=="NA"] <- NULL
> length(z)
[1] 7
```
Any suggestions on this?

**Comment by int19h** [comment]
Makes sense with vectors, since NULL is not an atomic type.

With lists, I think that's because your second assignment is a slicing assignment. You should be able to assign individual elements via `[[...]] <-`.

Also, perhaps `lapply` would work better here?

**Pull request merged**
