### PR TITLE
Enable non-generic login prompt.

### PR DESCRIPTION
**Pull request by karthiknadig**

### CODE REVIEW

**Comment by MikhailArkhipov** [comment]
👍

**Comment by MikhailArkhipov** [comment]
Can you also fix #2990 same PR

**Comment by karthiknadig** [comment]
Will do.

**Comment by karthiknadig** [comment]
For now it shows all the available options for the logon prompt. Pin pass will not work, user will need to select the username password option and enter it there. I have yet to figure out a clean way to unpack the pin-pass data. There is no indication that the packed data i receive from the prompt is username-pass or pin-pass.

**Comment by MikhailArkhipov** [comment]
👍

**Pull request merged**
