### PR TITLE
Preview data grid is read only

### PR DESCRIPTION
**Pull request by JeongPyoHam**

### CODE REVIEW

**Comment by huguesv** [comment]
👍

**Comment by JeongPyoHam** [comment]
thanks

**Comment by MikhailArkhipov** [comment]
Don't merge I am working on #1557

**Comment by MikhailArkhipov** [comment]
It needs more changes and more styling

**Comment by MikhailArkhipov** [comment]
On the other hand, go ahead, it wont conflict :+1:

**Comment by JeongPyoHam** [comment]
Reverted. As for theme, I had a PR, 1523, which I just closed as change was not valid any longer after other guys changed same code base and were working. Referring to it might not be a complete waste of time.

**Pull request merged**
