### PR TITLE
Make FormulaTest pass on both R 3.2 and 3.3.

### PR DESCRIPTION
**Pull request by huguesv**
Fixes https://github.com/Microsoft/RTVS/issues/1887

### CODE REVIEW

**Comment by AlexanderSher** [comment]
Do we need to handle this anywhere in the product itself?

**Comment by int19h** [comment]
I don't think so. R changed the return value of `str()` for formulas, basically. But we don't really rely on it anywhere (and we shouldn't, precisely because it's not a stable parseable representation) - we just show it to the user.

**Comment by int19h** [comment]
This does however raise the question of what to do about such cases. Right now the test will be run using only one R version, so it will only be testing one of the possible two cases. We'll need to figure something out to make it, and other cases like it, run on different R versions for our nightlies.

**Comment by AlexanderSher** [comment]
:+1:

**Pull request merged**
