### PR TITLE
Interactive Window update

### PR DESCRIPTION
**Pull request by karthiknadig**

### CODE REVIEW

**Comment by MikhailArkhipov** [comment]
You need to add new assembly to setup authoring, see Assemblies.wxi in Setup project.

**Comment by AlexanderSher** [comment]
What is `Microsoft.R.InteractiveWindow.dll`? Where is the source code for it?

**Comment by karthiknadig** [comment]
It is the most recent version of the interactive window, which is identical to the one used by python tools and roslyn. It was built out of the clone of roslyn here, https://github.com/zooba/VsInteractiveWindow

**Comment by AlexanderSher** [comment]
Ok, I'd like to get more details. Are we going to have 3 different assemblies of Interactive Window that will contain identical code that just sits in different namespaces?

**Comment by karthiknadig** [comment]
Yes, that is correct.

**Comment by MikhailArkhipov** [comment]
One more thing: there is Setup.15.0 project and new assemblies need to be added to files.swr.

**Comment by MikhailArkhipov** [comment]
:+1:

**Comment by karthiknadig** [comment]
Closing this pull request. Bad merge :(

**Pull request closed without merging**
