### PR TITLE
Add icons to variables in Variable Explorer:

### PR DESCRIPTION
**Pull request by int19h**
- active bindings
- promises
- functions
- data frames
- matrices
- errors
- normal variables (everything else)

### CODE REVIEW

**Comment by int19h** [comment]
Here are all the icons that are readily available:

http://glyphlist.azurewebsites.net/knownmonikers/

If you can think of anything else from there that we could use for some category of variables, let me know.

**Comment by int19h** [comment]
image

**Comment by int19h** [comment]
Alternatively, we could abandon standard VS mappings (which are kinda weird - like, why is method a transparent box?), and do something like this:

 Scalar values (1-element vectors, NULL etc)

 Vectors (except 1-element), lists

 Environments

 S4 objects (including ref class instances)

 Ref class definitions / constructors

 Functions

 Language objects (symbols and calls)

 Matrices

 Data frames

 Formulas

 Active bindings (e.g. ref class properties)

 Promises

**Comment by smortaz** [comment]
+1

**Comment by huguesv** [comment]
I like your alternative icons proposal.

**Comment by int19h** [comment]
image

**Comment by int19h** [comment]
One annoyance that I see now is that, because most of these icons are grey, they blend with the variable name, whereas the colored debugger icons did not. However, a uniform color could be added easily, so long as we can decide what it should be. Bikeshedding time!

**Comment by MikhailArkhipov** [comment]
Looks crowded... I'd probably drop icons on ```[[x]]``` they are self-explanatory

**Comment by int19h** [comment]
The icons are assigned based on the type/class. Note that it is possible for a list element to be an S4 object or an environment, for example (look at `envFoo@foo` to see one such case).

Maybe drop the icons for scalars?

**Comment by int19h** [comment]
It seems that the distance between icon and name was very small, significantly contributing to the cluttered appearance. Here it is with the spacing increased 4x (and dark theme, but that doesn't really make a difference):

image

**Comment by int19h** [comment]
Another option is to make the icons more subdued by blending them into the background. This is 50% alpha:

image

**Comment by huguesv** [comment]
I don't like the 50% alpha very much.
Margin is 4 in the combo box, vs. 8 in the list.
Solution explorer looks like it may be using 6, should we use that?

**Comment by huguesv** [comment]
Otherwise :+1: on the code changes.

**Comment by MikhailArkhipov** [comment]
Actually faded looks better. Still not sure about icons on simple values but we'll see what users say.

:+1:

**Pull request merged**
