### PR TITLE
Couple of bug fixes

### LINKED ISSUE #3459: Error in project settings UI Run page
Add value to collection of type 'System.Windows.Controls.ColumnDefinitionCollection' threw an exception.

image

Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.2 (26424.2-Preview) d15rel Internal Preview - Dogfood
VisualStudio.15.IntPreview/15.2.0-Preview+26424.2.d15rel
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Visual Basic 2017   00369-60000-00001-AA743
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA743
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA743
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.6.00404.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30404.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   3.0.17114.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Hive Query Language Service   2.2.5000.0
Language service for Hive query

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   4.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Python   3.0.17114.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   3.0.17114.1
Provides templates and integration for the Django web framework.

Python - IronPython support   3.0.17114.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   3.0.17114.1
Profiling support for Python projects.

R Tools for Visual Studio   1.1.30428.1005
Provides project system, R Interactive window, plotting, and more for the R programming language.

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.2.2.0
TypeScript tools for Visual Studio

### PR DESCRIPTION
**Pull request by AlexanderSher**
- Fix #3459: Error in project settings UI Run page
- Fix context menu crash in VE

### CODE REVIEW

**Comment by huguesv** [comment]
👍

**Comment by MikhailArkhipov** [comment]
BTW, what changed? I tried in RTM and VE doesn't open. `.2` is incompatible?

**Comment by MikhailArkhipov** [comment]
```
   at System.Windows.ResourceDictionary.SetDeferrableContent(DeferrableContent deferrableContent)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__297_0(Object target, Object value)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
```

`Cannot re-initialize ResourceDictionary instance.`

**Comment by AlexanderSher** [comment]
#3460 had a different error and I couldn't reproduce it locally. Do you have a full stack trace?

**Comment by MikhailArkhipov** [comment]
2015 works fine with F5

```
>	PresentationFramework.dll!System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader xamlReader, System.Xaml.IXamlObjectWriterFactory writerFactory, bool skipJournaledProperties, object rootObject, System.Xaml.XamlObjectWriterSettings settings, System.Uri baseUri)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader xamlReader, bool skipJournaledProperties, object rootObject, System.Xaml.Permissions.XamlAccessLevel accessLevel, System.Uri baseUri)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream stream, System.Windows.Markup.ParserContext parserContext, object parent, bool closeStream)	Unknown
 	PresentationFramework.dll!System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream stream, System.Windows.Markup.ParserContext pc)	Unknown
 	PresentationFramework.dll!MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(System.IO.Stream stream, System.Uri baseUri, bool canUseTopLevelBrowser, bool sandboxExternalContent, bool allowAsync, bool isJournalNavigation, out System.Windows.Markup.XamlReader asyncObjectConverter)	Unknown
 	PresentationFramework.dll!MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(System.IO.Stream s, MS.Internal.ContentType contentType, System.Uri baseUri, bool canUseTopLevelBrowser, bool sandboxExternalContent, bool allowAsync, bool isJournalNavigation, out System.Windows.Markup.XamlReader asyncObjectConverter)	Unknown
 	PresentationFramework.dll!System.Windows.ResourceDictionary.Source.set(System.Uri value)	Unknown
 	PresentationFramework.dll!System.Windows.Baml2006.WpfSharedBamlSchemaContext.Create_BamlProperty_ResourceDictionary_Source.AnonymousMethod__342_0(object target, object value)	Unknown
 	PresentationFramework.dll!System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(object instance, object value)	Unknown
 	System.Xaml.dll!MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(System.Xaml.XamlMember member, object obj, object value)	Unknown
 	System.Xaml.dll!MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(object inst, System.Xaml.XamlMember property, object value)	Unknown
 	System.Xaml.dll!MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.SetValue(object obj, System.Xaml.XamlMember property, object value)	Unknown
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.Logic_ApplyPropertyValue(MS.Internal.Xaml.Context.ObjectWriterContext ctx, System.Xaml.XamlMember prop, object value, bool onParent)	Unknown
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.Logic_DoAssignmentToParentProperty(MS.Internal.Xaml.Context.ObjectWriterContext ctx)	Unknown
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(MS.Internal.Xaml.Context.ObjectWriterContext ctx)	Unknown
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.WriteEndMember()	Unknown
 	System.Xaml.dll!System.Xaml.XamlWriter.WriteNode(System.Xaml.XamlReader reader)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.WpfXamlLoader.TransformNodes(System.Xaml.XamlReader xamlReader, System.Xaml.XamlObjectWriter xamlWriter, bool onlyLoadOneNode, bool skipJournaledProperties, bool shouldPassLineNumberInfo, System.Xaml.IXamlLineInfo xamlLineInfo, System.Xaml.IXamlLineInfoConsumer xamlLineInfoConsumer, MS.Internal.Xaml.Context.XamlContextStack<System.Windows.Markup.WpfXamlFrame> stack, System.Windows.Markup.IStyleConnector styleConnector)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader xamlReader, System.Xaml.IXamlObjectWriterFactory writerFactory, bool skipJournaledProperties, object rootObject, System.Xaml.XamlObjectWriterSettings settings, System.Uri baseUri)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader xamlReader, bool skipJournaledProperties, object rootObject, System.Xaml.Permissions.XamlAccessLevel accessLevel, System.Uri baseUri)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream stream, System.Windows.Markup.ParserContext parserContext, object parent, bool closeStream)	Unknown
 	PresentationFramework.dll!System.Windows.Application.LoadComponent(object component, System.Uri resourceLocator)	Unknown
 	Microsoft.VisualStudio.R.Package.dll!Microsoft.VisualStudio.R.Package.DataInspect.VariableView.InitializeComponent()	Unknown
 	Microsoft.VisualStudio.R.Package.dll!Microsoft.VisualStudio.R.Package.DataInspect.VariableView.VariableView(Microsoft.R.Support.Settings.IRToolsSettings settings, Microsoft.Common.Core.Shell.ICoreShell shell)	Unknown
 	Microsoft.VisualStudio.R.Package.dll!Microsoft.VisualStudio.R.Package.DataInspect.VariableWindowPane.VariableWindowPane()	Unknown

```

**Comment by MikhailArkhipov** [comment]
image

**Comment by MikhailArkhipov** [comment]
Can't repro with F5

**Pull request merged**
