### PR TITLE
Couple of fixes.

### PR DESCRIPTION
**Pull request by karthiknadig**
* #2111 Unified RSession blob send, get, and destroy methods.
* #2112 Added negative tests for Send, Get, and Destroy Blobs.

### CODE REVIEW

**Comment by karthiknadig** [comment]
I have a update to this after recent merge.

**Comment by AlexanderSher** [comment]
Is it in PR?

**Comment by karthiknadig** [comment]
No. I am doing this now.

**Comment by AlexanderSher** [comment]
:+1:

**Pull request merged**
