### PR TITLE
#1410: Package Manager UI: Details should show package title

### PR DESCRIPTION
**Pull request by MikhailArkhipov**

### CODE REVIEW

**Comment by huguesv** [comment]
I was thinking we show both title and description.

**Comment by MikhailArkhipov** [comment]
They may be duplicate text... Description is often missing however.

**Comment by int19h** [comment]
Don't we already show title in XAML?

**Comment by int19h** [comment]
Ah, I see now, title != package name. 

In details, I think it would be most appropriate to show both title and description.

**Comment by huguesv** [comment]
We show it in the tooltip in the left pane.  I'd like us to show it at the top in the details pane.

Description shouldn't be missing.  It's a mandatory field:
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file

Right now Description is missing from installed packages, but that's a bug and will be fixed.
https://github.com/Microsoft/RTVS/issues/1439

**Comment by MikhailArkhipov** [comment]
Nope.

image

We could do NuGet style

image

**Comment by MikhailArkhipov** [comment]
Maybe I misunderstood the bug but Description comes empty in 

            return new RPackageViewModel(package.Package) {

**Comment by AlexanderSher** [comment]
Guys, I've already added a row with title to the Details
So you can leave this bug on me

**Comment by MikhailArkhipov** [comment]
Maybe the bug is actually in fetching descriptions then...

**Comment by MikhailArkhipov** [comment]
OK

**Comment by AlexanderSher** [comment]
> Maybe the bug is actually in fetching descriptions then...

https://github.com/Microsoft/RTVS/issues/1439

**Pull request closed without merging**
